# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

disbursement_job:
  class: Disbursement::Job
  queue: default
  schedule: every day at 8am

monthly_fee_job:
  class: MinimumMonthlyFee::Job
  queue: default
  schedule: every month at 1